name: New Protocol Integration
description: Building adapters and other tech
title: "[Feature]: "
labels: ["feature-request"]
projects: ["Gearbox Ops"]
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this asset onboarding form!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: protocol
    attributes:
      label: Protocol
      description: Please provide protocol name
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Also tell us, why you think this integration is valuable? 
      placeholder: Tell us what you see!
      value: "Motivation"
    validations:
      required: true
  - type: input
    id: tvl
    attributes:
      label: TVL
      description: Please provide information on how much TVL has protocol.
    validations:
      required: true
  - type: textarea
    id: contracts
    attributes:
      label: Contracts
      description: Please provide link to deployed contracts and links to smart-contracts repositories. 
      render: shell
    validations:
      required: true
  - type: textarea
    id: audits
    attributes:
      label: Audits
      description: Please provide list of audits for protocol.
      render: shell
    validations:
      required: true
